name: cron

on:
  workflow_dispatch:
#  schedule:
#    - cron: '0 8 * * *'

jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Run npm steps
        run: |
          cd ..
          # git clone https://github.com/abap-openapi/abap-openapi.git
          git clone --single-branch --branch cli-for-v2 https://github.com/gregorwolf/abap-openapi.git
          cd abap-openapi
          npm install && npm transpile
          mkdir test_v2/test100
          node test_v2/index.mjs https://raw.githubusercontent.com/gregorwolf/sap-malware-scanning-openapi/main/src/MalwareScanAPI.json test_v2/test100 mwscan
          cp ./test_v2/test100/*.abap ../generated-sap-malware-scanning-openapi/src/
          git status
      - name: Push
        if: github.ref == 'refs/heads/main'
        run: |
          git status
          git config --global user.email "actions@github.com"
          git config --global user.name "Actions CI"
          git add -A
          git diff-index --quiet HEAD || git commit -m "Automatic update"
          git push
